import katex from 'katex';
import 'katex/dist/katex.min.css';
const root=document.querySelector<HTMLElement>('[data-cooling]')!;
const $=<T extends HTMLElement=HTMLElement>(s:string)=>root.querySelector<T>(s)!;
const base=root.dataset.endpoint||'',key='aero.cooling.screen.v1';
const defaults={heat_w:100,flow_ml_s:1,inlet_c:25,wall_limit_c:72,pressure_budget_pa:2000,length_mm:500,available_width_mm:12};
type Message={role:'user'|'assistant'|'guide';content:string};
let state:{inputs:Record<string,number|null>;reviewed:boolean;messages:Message[];id?:string;requestId?:string;status?:any;result?:any}={inputs:{...defaults,length_mm:null,available_width_mm:null},reviewed:false,messages:[]};
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.inputs&&Array.isArray(saved.messages))state=saved;}catch{}
let step=0,online=false,connected=false,busy=false,submitting=false,disposer:(()=>void)|undefined,viewTicket=0,pollTimer:ReturnType<typeof setTimeout>|undefined;
const working=()=>submitting||['queued','running'].includes(state.status?.state);
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{$('[data-notice]').textContent='Browser storage is unavailable. Download your paper before leaving.';}}
function missing(){return [...root.querySelectorAll<HTMLInputElement>('[data-input]')].filter(i=>state.inputs[i.dataset.input!]===null||!Number.isFinite(state.inputs[i.dataset.input!] as number)||(state.inputs[i.dataset.input!] as number)<Number(i.min)||(state.inputs[i.dataset.input!] as number)>Number(i.max));}
function showMessages(){const host=$('[data-conversation]');host.replaceChildren();for(const m of state.messages){const a=document.createElement('article'),label=document.createElement('small'),p=document.createElement('p');label.textContent=m.role==='user'?'YOU':m.role==='guide'?'REQUIREMENTS CHECK · NOT A MODEL REPLY':'AERO · LIVE MODEL';p.textContent=m.content;a.append(label,p);host.append(a);}host.scrollTop=host.scrollHeight;}
async function request(path:string,body?:unknown){if(path==='/chat'&&body)body={...(body as object),cooling_inputs:structuredClone(state.inputs)};if(path==='/study/cooling/runs'&&state.status?.state==='failed'){state.requestId=crypto.randomUUID();body={...(body as object),request_id:state.requestId};save();}const r=await fetch(base+path,{method:body?'POST':'GET',credentials:'omit',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(120000)});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.error||`Request failed (${r.status})`),{status:r.status});return data;}
const f=(n:number)=>Number(n).toLocaleString(undefined,{maximumFractionDigits:2});
function render(){
  root.querySelectorAll<HTMLInputElement>('[data-input]').forEach(i=>{i.value=state.inputs[i.dataset.input!]===null?'':String(state.inputs[i.dataset.input!]);i.disabled=working();});
  const needs=missing();$('[data-missing]').textContent=needs.length?'Needed next: '+needs.map(i=>i.parentElement?.firstChild?.textContent?.trim()).join(', ')+'. Ask Aero why, then fill the controls.':'Dimensions supplied. Review the assumptions before starting.';
  $<HTMLInputElement>('[data-confirm]').checked=state.reviewed;$<HTMLInputElement>('[data-confirm]').disabled=working()||needs.length>0;
  $<HTMLButtonElement>('[data-prepare]').disabled=needs.length>0||!state.reviewed;
  $<HTMLButtonElement>('[data-example]').disabled=working();
  $<HTMLButtonElement>('[data-run]').disabled=needs.length>0||!state.reviewed||!online||working()||Boolean(state.result);
  $('[data-run]').textContent=state.result?'Complete — open Report':working()?'Preparing report…':'Start analytical study + PDF';
  $('[data-heading]').textContent=['Define heat, flow and limits.','Separate bulk rise from wall temperature.','Inspect the three candidate layouts.','Run the analytical comparison.','Make the decision with evidence.'][step];
  root.querySelectorAll<HTMLElement>('[data-part]').forEach(el=>el.hidden=Number(el.dataset.part)!==step);
  root.querySelectorAll<HTMLElement>('[data-stage]').forEach((el,i)=>{el.setAttribute('aria-current',i===step?'step':'false');el.dataset.done=String(Boolean(state.result));const percent=state.result?100:i===0?Math.round((7-needs.length)/7*100):state.reviewed?100:Math.round((7-needs.length)/7*80);el.querySelector('progress')!.value=percent;el.querySelector('[data-progress-label]')!.textContent=state.result?'Complete':i===0?`${percent}% supplied`:working()&&i>=3?'In progress':state.reviewed?'Ready to inspect':'Needs review';});
  const job=$('[data-job]');job.hidden=!state.status||step<3;job.dataset.state=state.status?.state||'';
  if(state.status){$('[data-job-label]').textContent=state.status.state;$('[data-job-message]').textContent=state.status.message;$<HTMLProgressElement>('[data-job-progress]').value=state.status.completed||0;}
  $('[data-downloads]').hidden=!state.result;
  if(state.result){const r=state.result;$('[data-decision]').textContent=r.decision;const table=document.createElement('table');const head=table.createTHead().insertRow();for(const name of ['Layout','Nominal wall °C','Guard wall °C','Guard Δp Pa','Disposition']){const th=document.createElement('th');th.textContent=name;head.append(th);}for(const v of r.layouts){const tr=table.insertRow();for(const value of [v.id,f(v.wall_c),f(v.guard_wall_c),f(v.guard_pressure_pa),v.passes?'Pass':Object.entries(v.gates).filter(([,ok])=>!ok).map(([name])=>name.replaceAll('_',' ')).join(', ')]){tr.insertCell().textContent=value;}}$('[data-table]').replaceChildren(table);
    $('[data-result-chart]').replaceChildren();for(const v of r.layouts){const row=document.createElement('div');row.className='result-bar';row.dataset.pass=String(v.passes);const label=document.createElement('span'),bar=document.createElement('i'),value=document.createElement('span');label.textContent='Layout '+v.id;bar.style.width=Math.min(100,v.guard_wall_c/100*100)+'%';value.textContent=f(v.guard_wall_c)+' °C';row.append(label,bar,value);$('[data-result-chart]').append(row);}
    $('[data-checks]').textContent=`Guard wall estimates above. Energy and radial-equation verification: ${r.checks_passed?'passed':'review needed'}. Thermal CFD: not performed.`;
    $<HTMLAnchorElement>('[data-pdf]').href=base+'/study/runs/'+state.id+'/paper';$<HTMLAnchorElement>('[data-evidence]').href=base+'/study/runs/'+state.id+'/evidence';
  }else{$('[data-decision]').textContent='No result for the current inputs.';$('[data-table]').replaceChildren();$('[data-result-chart]').replaceChildren();$('[data-checks]').textContent='';}
  $<HTMLButtonElement>('[data-back]').disabled=step===0;$<HTMLButtonElement>('[data-next]').disabled=step===4;
  $('[data-next]').textContent=['Math →','Layouts →','Compare →','Report →','Complete'][step];$('[data-step-note]').textContent=state.result?'Paper and evidence ready':working()?'Report in progress':'Review each stage before execution';
  if(step===2)void geometry();else{viewTicket++;disposer?.();disposer=undefined;}
}
function move(i:number){step=i;render();}
function invalidate(){state.reviewed=false;state.id=undefined;state.requestId=undefined;state.status=undefined;state.result=undefined;if(pollTimer)clearTimeout(pollTimer);$('[data-notice]').textContent='Inputs changed. The previous result no longer applies; review and run again.';save();render();}
root.querySelectorAll<HTMLInputElement>('[data-input]').forEach(i=>i.addEventListener('change',()=>{state.inputs[i.dataset.input!]=i.value===''?null:Number(i.value);invalidate();}));
$('[data-confirm]').addEventListener('change',()=>{state.reviewed=$<HTMLInputElement>('[data-confirm]').checked;save();render();});
$('[data-example]').addEventListener('click',()=>{state.inputs={...defaults};invalidate();state.messages.push({role:'guide',content:'Worked example loaded: 100 W into water at 1 mL/s, 25 °C inlet, 72 °C inner-wall limit and 2,000 Pa straight-channel budget. Length 500 mm; available width 12 mm. Review these assumed requirements before calculating.'});save();showMessages();move(0);});
root.querySelectorAll<HTMLElement>('[data-stage]').forEach((b,i)=>b.addEventListener('click',()=>move(i)));$('[data-back]').addEventListener('click',()=>move(Math.max(0,step-1)));$('[data-next]').addEventListener('click',()=>move(Math.min(4,step+1)));$('[data-prepare]').addEventListener('click',()=>move(1));
for(const equation of [String.raw`T_{b,o}=T_{b,i}+\frac{Q}{\rho\dot Vc_p}`,String.raw`Nu=\frac{48}{11},\quad h=\frac{Nu k}{D}`,String.raw`T_{w,o}=T_{b,o}+\frac{Q}{hN\pi DL}`,String.raw`\Delta p=\frac{128\mu L\dot V}{N\pi D^4},\quad P_{hyd}=\Delta p\dot V`]){const el=document.createElement('div');katex.render(equation,el,{displayMode:true,trust:false});$('[data-math]').append(el);}
async function geometry(){const ticket=++viewTicket;disposer?.();disposer=undefined;const idx=Number($<HTMLSelectElement>('[data-layout]').value),[n,d]=[[4,1],[2,2],[1,4]][idx],L=Number(state.inputs.length_mm);$('[data-layout-size]').textContent=`${n} passages · Ø ${d} mm · ${(L||0)} mm long`;if(!L){$('[data-geometry]').textContent='Supply heated length before inspecting geometry.';return;}try{const {coolingGeometry}=await import('./cooling-view');if(ticket!==viewTicket)return;disposer=coolingGeometry($('[data-geometry]'),L,n,d);}catch{$('[data-geometry]').textContent='3D unavailable. Dimensions and the PDF remain available.';}}
$('[data-layout]').addEventListener('change',()=>void geometry());
async function poll(){const id=state.id;if(!id)return;try{state.status=await request('/study/runs/'+id);if(state.status.state==='complete'){state.result=await request('/study/runs/'+id+'/result');if(state.result.source!=='ANALYTICAL_SCREENING')throw Object.assign(Error('Unexpected study result type'),{status:409});$('[data-notice]').textContent='Comparison and PDF complete. Open Report.';}save();render();if(!['complete','failed'].includes(state.status.state))pollTimer=setTimeout(()=>void poll(),2000);}catch(e){const error=e as Error&{status?:number};if([404,409].includes(error.status||0)){state.result=undefined;state.status={state:'failed',message:error.message};save();render();}else pollTimer=setTimeout(()=>void poll(),10000);$('[data-notice]').textContent=error.message+' Your run link is saved; refresh after reconnecting or start a fresh study if expired.';}}
$('[data-run]').addEventListener('click',async()=>{if(!state.reviewed||missing().length||working()||state.result)return;submitting=true;state.requestId ||=crypto.randomUUID();save();render();try{const r=await request('/study/cooling/runs',{request_id:state.requestId,inputs:state.inputs});state.id=r.id;state.status={state:'queued',message:'Queued for analytical calculation and PDF generation',completed:0};save();void poll();}catch(e){$('[data-notice]').textContent=(e as Error).message;}finally{submitting=false;render();}});
$('[data-chat]').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const input=$<HTMLTextAreaElement>('#question'),content=input.value.trim();if(!content)return;if(!connected){$('[data-model]').textContent='Model offline. Numerical study controls remain usable when the report worker is online.';return;}busy=true;$<HTMLButtonElement>('[data-send]').disabled=true;const messages=[...state.messages.filter(m=>m.role!=='guide'),{role:'user' as const,content}].slice(-10);while(messages.length>1&&messages.reduce((n,m)=>n+m.content.length,0)>16000)messages.shift();try{const r=await request('/chat',{messages,requirements:{goal:'Analytical forced-convection circular-passage screening, not CFD. Explain or ask the next missing requirement. User must edit controls; do not claim to have changed them.',geometry:`Layouts 4 x 1 mm, 2 x 2 mm, 1 x 4 mm; equal split; heated length ${state.inputs.length_mm??'MISSING'} mm; available width ${state.inputs.available_width_mm??'MISSING'} mm.`,fluid:'Water fixed near 25 C; rho997, cp4180, mu0.00089, k0.607. Fully developed laminar, uniform all-perimeter heat flux.',conditions:JSON.stringify(state.inputs),success:'Wetted inner wall and straight-passage friction budgets only; guard thermal Q+10%, flow-10%, h-20%. Solid and manifold effects excluded.',reference:state.result?JSON.stringify({source:state.result.source,decision:state.result.decision,limits:state.result.limits}):'No calculation performed yet. Ask for missing heated length and width.'}});if(!r.ok||typeof r.reply!=='string')throw Error('Invalid model reply');state.messages.push({role:'user',content},{role:'assistant',content:r.reply});state.messages=state.messages.slice(-80);input.value='';save();showMessages();}catch(error){$('[data-model]').textContent=(error as Error).message;}finally{busy=false;$<HTMLButtonElement>('[data-send]').disabled=false;}});
async function health(){try{online=(await request('/study/health')).ready===true;}catch{online=false;}try{const h=await request('/health');connected=h.ready===true&&h.mode==='conversation_only';$('[data-model]').textContent=connected?`${h.model} · live conversation`:'Model offline';}catch{connected=false;$('[data-model]').textContent='Model offline';}render();}
if(!state.messages.length)state.messages.push({role:'guide',content:'Before comparing cooling layouts, what heated length and channel-array width are available? The controls start with sample heat and flow values; confirm or replace them. Ask the live model for help below.'});
showMessages();render();void health();setInterval(()=>{if(!document.hidden)void health();},45000);if(state.id&&!state.result&&state.status?.state!=='failed')void poll();
