"""Curate an authoritative Aero wall-refinement result for static publishing.

The pressure surface is generated by Aero's bounded VTK projector before this
script runs. This step removes local-only fields and deterministically
downsamples real telemetry for a browser-sized public record; it never
recomputes an engineering verdict.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import shutil
from pathlib import Path
from typing import Any, Dict, List


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def downsample(points: List[Dict[str, Any]], maximum: int = 240) -> List[Dict[str, Any]]:
    if len(points) <= maximum:
        return points
    step = math.ceil((len(points) - 1) / (maximum - 1))
    selected = points[::step]
    if selected[-1] != points[-1]:
        selected.append(points[-1])
    return selected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--result", type=Path, required=True)
    parser.add_argument("--stl", type=Path, required=True)
    parser.add_argument("--surface", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source = json.loads(args.result.read_text(encoding="utf-8"))
    telemetry = source.get("telemetry") or {}
    curated_telemetry = {
        "residuals": {
            name: downsample(points)
            for name, points in (telemetry.get("residuals") or {}).items()
        },
        "massConservation": downsample(telemetry.get("massConservation") or []),
        "energyConservation": downsample(telemetry.get("energyConservation") or []),
        "monitors": {
            name: downsample(points)
            for name, points in (telemetry.get("monitors") or {}).items()
        },
    }
    retained_keys = (
        "schema", "evidenceSchema", "case", "execution", "inputs",
        "numerical", "readiness", "telemetrySummary", "analyticalExpectations",
        "geometryManifest", "meshStudy", "provenance", "interpretation",
    )
    curated = {key: source[key] for key in retained_keys if key in source}
    curated["telemetry"] = curated_telemetry
    curated["publicCuration"] = {
        "schema": "aero.public.curation.v1",
        "sourceEngineeringResultSha256": sha256(args.result),
        "telemetryPolicy": "real recorded samples only; deterministic endpoint-preserving downsample to at most 240 points per series",
        "rawSolverLogPublished": False,
        "localPathsPublished": False,
        "credentialsPublished": False,
    }

    args.output.mkdir(parents=True, exist_ok=True)
    result_out = args.output / "engineering-result.json"
    result_out.write_bytes(
        (json.dumps(curated, indent=2, sort_keys=True, allow_nan=False) + "\n").encode("utf-8")
    )
    shutil.copyfile(args.stl, args.output / "nozzle.stl")
    files = ("engineering-result.json", "pressure-surface.json", "nozzle.stl")
    checksums = {
        "schema": "aero.public.demo.checksums.v1",
        "algorithm": "SHA-256",
        "files": {name: sha256(args.output / name) for name in files},
    }
    (args.output / "checksums.json").write_bytes(
        (json.dumps(checksums, indent=2, sort_keys=True) + "\n").encode("utf-8")
    )
    print(json.dumps({
        "resultBytes": result_out.stat().st_size,
        "sourceSha256": curated["publicCuration"]["sourceEngineeringResultSha256"],
        "series": {
            "residuals": {name: len(points) for name, points in curated_telemetry["residuals"].items()},
            "massConservation": len(curated_telemetry["massConservation"]),
            "energyConservation": len(curated_telemetry["energyConservation"]),
            "monitors": {name: len(points) for name, points in curated_telemetry["monitors"].items()},
        },
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
